const services = [
    { value: '', label: '-- Select Service --' },
    { value: 'TV Media', label: 'TV Media' },
    { value: 'TV Production and TVC', label: 'TV Production and TVC' },
    { value: 'TV PRDUCTION & TVC', label: 'TV PRDUCTION & TVC' },
    { value: 'RADIO MEDIA', label: 'RADIO MEDIA' },
    { value: 'SOCIAL MEDIA', label: 'SOCIAL MEDIA' },
    { value: 'Sponsorship', label: 'Sponsorship' },
    { value: 'PRESS AD', label: 'PRESS AD' },
    { value: 'OUTDOOR Billboard, Wall and Shutter Painting', label: 'OUTDOOR Billboard, Wall and Shutter Painting' },
    { value: 'SHOP SIGN & DECORATION', label: 'SHOP SIGN & DECORATION' },
    { value: 'Software development & other', label: 'Software development & other' },
    { value: 'Corporate Marketing Service', label: 'Corporate Marketing Service' },
    { value: 'Market research - retail audit', label: 'Market research - retail audit' },
    { value: 'Market Research', label: 'Market Research' },
    { value: 'Scratch card ,Mobile SMS, Recharge & Topup service', label: 'Scratch card ,Mobile SMS, Recharge & Topup service' },
    { value: 'Dealer Shop Merchandising', label: 'Dealer Shop Merchandising' },
    { value: 'Event management (Art Competition, Awards, Daily star anniversary)', label: 'Event management (Art Competition, Awards, Daily star anniversary)' },
    { value: 'Consumer promotion - Activation', label: 'Consumer promotion - Activation' },
    { value: 'Fair & Exhibition', label: 'Fair & Exhibition' },
    { value: 'Pack Design & Creative', label: 'Pack Design & Creative' },
    { value: 'Franchise Expense-Experience Zone', label: 'Franchise Expense-Experience Zone' },
    { value: 'Umbrella - courier', label: 'Umbrella - courier' },
    { value: 'Shomporko Club scheme', label: 'Shomporko Club scheme' },
    { value: 'PTI service', label: 'PTI service' }
];
const activityTypes = [
    { value: '', label: '-- Select Activity Type --' },
    { value: 'One Time', label: 'One Time' },
    { value: 'Monthly Recurring', label: 'Monthly Recurring' }
];

const budgetTypes = [
    { value: '', label: '-- Select Budget Type --' },
    { value: 'Available Budget', label: 'Available Budget' },
    { value: 'Need to Transfer', label: 'Need to Transfer' },
    { value: 'Supplementary', label: 'Supplementary' }
];

const brands = [
    { value: '', label: '-- Select Brand --' },
    { value: 'Adhesive -Power Bond', label: 'Adhesive -Power Bond', number: 500381 },
    { value: 'Adhesive -Tex Bond', label: 'Adhesive -Tex Bond', number: 500382 },
    { value: 'APE', label: 'APE', number: 500003 },
    { value: 'Auto Refinish', label: 'Auto Refinish', number: 500100 },
    { value: 'Berger Experience Zone (Decorative)', label: 'Berger Experience Zone (Decorative)', number: 502901 },
    { value: 'BREATHE EASY', label: 'BREATHE EASY', number: 500240 },
    { value: 'Color Bank', label: 'Color Bank', number: 500121 },
    { value: 'Corporate Brand', label: 'Corporate Brand', number: 500097 },
    { value: 'Mr.EXPERT DAMP GUARD', label: 'Mr.EXPERT DAMP GUARD', number: 503604 },
    { value: 'Decorative', label: 'Decorative', number: 500377 },
    { value: 'DUROCEM', label: 'DUROCEM', number: 500094 },
    { value: 'EASY CLEAN', label: 'EASY CLEAN', number: 500004 },
    { value: 'EP Tools (Express Painting)', label: 'EP Tools (Express Painting)', number: 500420 },
    { value: 'Express Painting Service', label: 'Express Painting Service', number: 502820 },
    { value: 'Home Décor Branding', label: 'Home Décor Branding', number: 500120 },
    { value: 'Industrial Paints', label: 'Industrial Paints', number: 500378 },
    { value: 'INNOVA', label: 'INNOVA', number: 500020 },
    { value: 'JHILIK', label: 'JHILIK', number: 500011 },
    { value: 'LS. Metallic Finish', label: 'LS. Metallic Finish', number: 502800 },
    { value: 'LSE', label: 'LSE', number: 500007 },
    { value: 'Marine Paints', label: 'Marine Paints', number: 500379 },
    { value: 'Mr.EXPERT DAMP GUARD', label: 'Mr.EXPERT DAMP GUARD', number: 503604 },
    { value: 'Painters App', label: 'Painters App', number: 503621 },
    { value: 'Powder Coating', label: 'Powder Coating', number: 500380 },
    { value: 'PRE TREATMENT CHEM', label: 'PRE TREATMENT CHEM', number: 500096 },
    { value: 'Printing Ink', label: 'Printing Ink', number: 502840 },
    { value: 'REX', label: 'REX', number: 500181 },
    { value: 'RIN', label: 'RIN', number: 500180 },
    { value: 'ROBB WALL PUTTY', label: 'ROBB WALL PUTTY', number: 500015 },
    { value: 'ROBB WATER SEALER', label: 'ROBB WATER SEALER', number: 500014 },
    { value: 'RSE', label: 'RSE', number: 500000 },
    { value: 'Salt Safe', label: 'Salt Safe', number: 500303 },
    { value: 'SPD', label: 'SPD', number: 500009 },
    { value: 'Touch putty (Decorative)', label: 'Touch putty (Decorative)', number: 502900 },
    { value: 'Value Club App, LMS, Happy Wallet, MR/VR', label: 'Value Club App, LMS, Happy Wallet, MR/VR', number: 503620 },
    { value: 'Auto Refinish', label: 'Auto Refinish', number: 500100 },
    { value: 'W/C ANTIDIRT', label: 'W/C ANTIDIRT', number: 500351 },
    { value: 'W/C ANTIDIRT LONGLIFE (F167)', label: 'W/C ANTIDIRT LONGLIFE (F167)', number: 500401 },
    { value: 'W/C Antidirt Supreme (F168)', label: 'W/C Antidirt Supreme (F168)', number: 502880 },
    { value: 'WEATHER COAT EXTERIOR SEALER', label: 'WEATHER COAT EXTERIOR SEALER', number: 500200 },
    { value: 'W/C SMOOTH', label: 'W/C SMOOTH', number: 500026 },
    { value: 'WC GLOW', label: 'WC GLOW', number: 503574 },
    { value: 'WEATHER COAT EXTERIOR SEALER', label: 'WEATHER COAT EXTERIOR SEALER', number: 500200 },
    { value: 'Wood Coating / Innova', label: 'Wood Coating / Innova', number: 500383 },
    { value: 'WOOD KEEPER', label: 'WOOD KEEPER', number: 500033 },
    { value: 'Xpress Sealer (Decorative)', label: 'Xpress Sealer (Decorative)', number: 502860 }
];
const commitmentItems = [
    { value: '', label: '-- Select Commitment Item --' },
    { value: 'TVC Spot/ Popup', label: 'TVC Spot/ Popup', number: '7400000S01B01A01E01R01' },
    { value: 'TVC Production', label: 'TVC Production', number: '7400001S01B01A01E01R01' },
    { value: 'Press Ad', label: 'Press Ad', number: '7400004S01B01A01E01R01' },
    { value: 'Sponsorship Cost', label: 'Sponsorship Cost', number: '7400005S01B01A03E01R03' },
    { value: 'Social Media Buying', label: 'Social Media Buying', number: '7400006S01B01A02E01R02' },
    { value: 'Social Media Buying_ACS', label: 'Social Media Buying_ACS', number: '7400006S01B01A02E01R05' },
    { value: 'Con Pro_Campaign Actv Cost', label: 'Con Pro_Campaign Actv Cost', number: '7400014S01B01A01E02R07' },
    { value: 'Merchandising_Shop Decor & Merchan', label: 'Merchandising_Shop Decor & Merchan', number: '7400016S01B01A01E01R01' },
    { value: 'Merchandising_Shop Branding', label: 'Merchandising_Shop Branding', number: '7400016S01B01A02E01R01' },
    { value: 'Shop Sign Installation', label: 'Shop Sign Installation', number: '7400018S01B01A01E01R01' },
    { value: 'Billboard/Unipole Rent', label: 'Billboard/Unipole Rent', number: '7400019S01B01A02E02R03' },
    { value: 'Wall Painting', label: 'Wall Painting', number: '7400025S01B01A01E01R01' },
    { value: 'Exclusive_Shutter Painting', label: 'Exclusive_Shutter Painting', number: '7400025S01B01A02E01R02' },
    { value: 'Regular_Shutter Painting', label: 'Regular_Shutter Painting', number: '7400025S01B01A02E02R02' },
    { value: 'Retail audit', label: 'Retail audit', number: '7400032S01B01A01E01R01' },
    { value: 'Market Survey', label: 'Market Survey', number: '7400033S01B01A01E01R02' },
    { value: 'Dhaka AutoParts Show', label: 'Dhaka AutoParts Show', number: '7400037S01B01A08E01R01' },
    { value: 'Rehab Fair - CTG', label: 'Rehab Fair - CTG', number: '7400037S01B01A01E01R01' },
    { value: 'Furniture Fair', label: 'Furniture Fair', number: '7400037S01B01A02E01R01' },
    { value: 'Courier Cost', label: 'Courier Cost', number: '7400038S01B01A01E01R01' },
    { value: 'Shomporko Scheme', label: 'Shomporko Scheme', number: '7400046S01B01A01E01R01' },
    { value: 'SC MobileBanking Reward', label: 'SC MobileBanking Reward', number: '7400048S01B01A01E01R02' },
    { value: 'BYPAC', label: 'BYPAC', number: '7400055S01B01A01E01R01' },
    { value: 'BASAB', label: 'BASAB', number: '7400055S01B01A02E01R01' },
    { value: 'Berger - ArchKU', label: 'Berger - ArchKU', number: '7400055S01B01A05E01R01' },
    { value: 'FFA DU Talented Stud', label: 'FFA DU Talented Stud', number: '7400055S01B01A03E01R01' },
    { value: 'BAEA', label: 'BAEA', number: '7400055S01B01A04E01R01' },
    { value: 'Berger - ArchKU', label: 'Berger - ArchKU', number: '7400055S01B01A05E01R01' },
    { value: 'Sponsorship', label: 'Sponsorship', number: '7400055S01B01A06E02R07' },
    { value: 'ArchAsia', label: 'ArchAsia', number: '7400055S01B01A07E01R01' },
    { value: 'Other CSR Activities', label: 'Other CSR Activities', number: '7400055S01B01A08E02R07' },
    { value: 'Pack Design Charge', label: 'Pack Design Charge', number: '7400058S01B01A01E01R01' },
    { value: 'Corporate - Other', label: 'Corporate - Other', number: '7400061S01B01A02E01R02' },
    { value: 'PTI Trainer Salary', label: 'PTI Trainer Salary', number: '7400067S01B01A01E01R01' },
    { value: 'PTI Food Cost', label: 'PTI Food Cost', number: '7400067S01B01A01E01R04' },
    { value: 'PTI Transportation Cost', label: 'PTI Transportation Cost', number: '7400067S01B01A01E01R03' },
    { value: 'PTI Others', label: 'PTI Others', number: '7400067S01B01A01E01R09' },
];
const vendorQuotations = [
    { value: '', label: '-- Select Required Vendor Quotation --' },
    { value: 'Minimum 3 parties', label: 'Minimum 3 parties' },
    { value: 'Single Vendor', label: 'Single Vendor' }
];